# Generated by Django 5.0.1 on 2024-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitnessAssesmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_activity",
                    models.CharField(
                        choices=[
                            ("Weightlifting", "Weightlifting"),
                            ("Running", "Running"),
                            ("Yoga", "Yoga"),
                            ("Cycling", "Cycling"),
                            ("Swimming", "Swimming"),
                            ("Other", "Other"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "weekly_training_hours",
                    models.CharField(
                        choices=[
                            ("1-5", "Less than 5"),
                            ("5-10", "5 to 10"),
                            ("11-15", "11 to 15"),
                            ("15-99", "More than 15"),
                            ("0", "I don't train"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "main_fitness_goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("endurance", "Endurance"),
                            ("general_health", "General Health"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "eating_habits_level",
                    models.CharField(
                        choices=[
                            ("0", "Poor"),
                            ("1", "Average"),
                            ("2", "Good"),
                            ("3", "Excelent"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "preferred_meal_frequency",
                    models.CharField(
                        choices=[
                            ("small_frequent", "Small and Frequent"),
                            ("large_less_frequent", "Larger, less Frequent"),
                            ("no_preference", "No Preference"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "energy_level_slumps",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("sometimes", "Sometimes"),
                            ("often", "Often"),
                            ("always", "Always"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "sleep_quality",
                    models.CharField(
                        choices=[
                            ("0", "Poor"),
                            ("1", "Average"),
                            ("2", "Good"),
                            ("3", "Excelent"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "stress_management_style",
                    models.CharField(
                        choices=[
                            ("0", "Poor"),
                            ("1", "Average"),
                            ("2", "Good"),
                            ("3", "Excelent"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
