# Generated by Django 5.0.1 on 2024-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assesments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessassesmentprofile",
            name="customer_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
