# Generated by Django 5.0.1 on 2024-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assesments", "0002_fitnessassesmentprofile_customer_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessassesmentprofile",
            name="age",
            field=models.DecimalField(
                decimal_places=0, max_digits=2, null=True, verbose_name="Age"
            ),
        ),
        migrations.AddField(
            model_name="fitnessassesmentprofile",
            name="height_cm",
            field=models.DecimalField(
                decimal_places=0, max_digits=3, null=True, verbose_name="Height(cm)"
            ),
        ),
        migrations.AddField(
            model_name="fitnessassesmentprofile",
            name="target_weight_kg",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Target Weight (kg)",
            ),
        ),
        migrations.AddField(
            model_name="fitnessassesmentprofile",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=1, max_digits=3, null=True, verbose_name="Weight(kg)"
            ),
        ),
    ]
