# Generated by Django 5.0.1 on 2024-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assesments", "0003_fitnessassesmentprofile_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessassesmentprofile",
            name="height_cm",
            field=models.DecimalField(
                decimal_places=1, max_digits=3, null=True, verbose_name="Height(cm)"
            ),
        ),
    ]
