# Generated by Django 5.0.1 on 2024-04-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assesments", "0004_alter_fitnessassesmentprofile_height_cm"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessassesmentprofile",
            name="workout_frequency",
            field=models.CharField(
                choices=[
                    ("0", "Minimal Physical Activity"),
                    ("1", "Regular Walks"),
                    ("2", "Exercise 1-2 times per week"),
                    ("3", "Exercise 3-5 days per week"),
                    ("4", "Exercise 5-7 days per week"),
                ],
                default="1",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessassesmentprofile",
            name="height_cm",
            field=models.DecimalField(
                decimal_places=1, max_digits=4, null=True, verbose_name="Height(cm)"
            ),
        ),
        migrations.AlterField(
            model_name="fitnessassesmentprofile",
            name="stress_management_style",
            field=models.CharField(
                choices=[
                    ("0", "Physical Exercise"),
                    ("1", "Mindfullness nad meditation"),
                    ("2", "Creative Outlets"),
                    ("3", "Social Support"),
                    ("4", "Relaxation Techniques"),
                    ("5", "Other"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessassesmentprofile",
            name="target_weight_kg",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Target Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="fitnessassesmentprofile",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=1, max_digits=4, null=True, verbose_name="Weight(kg)"
            ),
        ),
    ]
