# Generated by Django 5.0.1 on 2024-02-12 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_servicelistingpage_banner_image_and_more"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="service_image",
            field=models.ForeignKey(
                help_text="This image is used on a services listing page and it will              be cropped for optimization ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
