# Generated by Django 5.0.1 on 2024-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcategory_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='short_description',
            field=models.TextField(blank=True, help_text='A short description of the category, max. 250 characters.', max_length=250, null=True, verbose_name='Short Description'),
        ),
    ]
